/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ai.project.main;


import java.util.Observable;
import java.util.Observer;

import ai.project.panels.BFSPanel;
import ai.project.panels.BIDIPanel;
import ai.project.panels.DFSPanel;
import ai.project.panels.DLSPanel;
import ai.project.panels.IDSPanel;


/**
 *
 * @author Duru Dumebi Julian
 */
public class MainFrame extends javax.swing.JFrame implements Observer{

    private static MainFrame instance;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        dfsMenuItem = new javax.swing.JMenuItem();
        dlsMenuItem = new javax.swing.JMenuItem();
        idsMenuItem = new javax.swing.JMenuItem();
        bfsMenuItem = new javax.swing.JMenuItem();
        bsMenuItem = new javax.swing.JMenuItem();
        ucsMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        jMenu4.setText("Actions");

        newMenuItem.setText("Start");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(newMenuItem);

        menuBar.add(jMenu4);

        jMenu2.setText("UnInformed Search");

        dfsMenuItem.setText("Depth First Search");
        dfsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dfsMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(dfsMenuItem);

        dlsMenuItem.setText("Depth Limited Search");
        dlsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlsMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(dlsMenuItem);

        idsMenuItem.setText("Iterative Deepening Search");
        idsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(idsMenuItem);

        bfsMenuItem.setText("Breadth First Search");
        bfsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfsMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(bfsMenuItem);

        bsMenuItem.setText("Bidirectional Search");
        bsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(bsMenuItem);

        ucsMenuItem.setText("Uniform Cost Search");
        jMenu2.add(ucsMenuItem);

        menuBar.add(jMenu2);

        jMenu3.setText("Informed Search");
        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dfsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfsMenuItemActionPerformed
        // TODO add your handling code here:
        MainIFrame.getInstance().addPanel(new DFSPanel());
        MainIFrame.getInstance().setFrameTitle("Depth First Search");
    }//GEN-LAST:event_dfsMenuItemActionPerformed

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        // TODO add your handling code here:
        MainIFrame mainIFrame = MainIFrame.getInstance();
        desktopPane.add(mainIFrame);
        mainIFrame.setVisible(true);
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void dlsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlsMenuItemActionPerformed
        // TODO add your handling code here:
        MainIFrame.getInstance().addPanel(new DLSPanel());
        MainIFrame.getInstance().setFrameTitle("Depth Limited Search");
    }//GEN-LAST:event_dlsMenuItemActionPerformed

    private void idsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsMenuItemActionPerformed
        // TODO add your handling code here:
        MainIFrame.getInstance().addPanel(new IDSPanel());
        MainIFrame.getInstance().setFrameTitle("Iterative Deepening Search");
    }//GEN-LAST:event_idsMenuItemActionPerformed

    private void bfsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsMenuItemActionPerformed
        // TODO add your handling code here:
        MainIFrame.getInstance().addPanel(new BFSPanel());
        MainIFrame.getInstance().setFrameTitle("Breadth First Search");
    }//GEN-LAST:event_bfsMenuItemActionPerformed

    private void bsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsMenuItemActionPerformed
        // TODO add your handling code here:
        MainIFrame.getInstance().addPanel(new BIDIPanel());
        MainIFrame.getInstance().setFrameTitle("Bidirectional Search");
    }//GEN-LAST:event_bsMenuItemActionPerformed

    @Override
    public void update(Observable o, Object arg){
        
    }
  
    public static synchronized MainFrame getInstance(){
        if (instance == null){
            instance = new MainFrame();
        }
        
        return instance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bfsMenuItem;
    private javax.swing.JMenuItem bsMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem dfsMenuItem;
    private javax.swing.JMenuItem dlsMenuItem;
    private javax.swing.JMenuItem idsMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem ucsMenuItem;
    // End of variables declaration//GEN-END:variables

 
}
